baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Ece Karabacak
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags 

params:
    description: "I am a 2D game artist from Turkey, passionate about cartoon and anime-inspired art, showcasing my work online while continuously exploring new creative challenges."
    author: Ece Karabacak
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: []
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ece Karabacak
          subtitle: "I am a 2D game artist from Turkey with a love for cartoon and anime-inspired art. My work focuses on vibrant, expressive characters and dynamic visuals. I showcase my projects and illustrations on my website, always exploring new styles and creative challenges. I studied Digital Game Design at Istanbul Bilgi University and continue to bring worlds to life through my art."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ecekar99@hotmail.com
        - name: artstation
          url: https://www.artstation.com/ecekarabacak
        - name: itchio
          url: http://karabacak.itch.io/
        - name: linkedin
          url: https://www.linkedin.com/in/ece-karabacak/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ece Karabacak"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2